### PR TITLE
Field allow null

### PR DESCRIPTION
**Pull request by anlcnydn**
Hey, there!

Hoping that this would fix [#3](https://github.com/swistakm/graceful/issues/3) and [#57](https://github.com/swistakm/graceful/issues/57). 

Tried to cover all cases as much as I can do, please let me know if I missed any. I will be waiting for reviews. 

Thanks in advance.

### CODE REVIEW

**Comment by swistakm** [comment]
Great! Thank you very much for contribution. It is perfect.

I will merge it now and mark it as release pending but I will release it after holidays as I will have plenty of time due to vacation. Is it OK?

**Comment by anlcnydn** [comment]
Of course, it is. Take your time. 

By the way, I know that you already knew it, but just in case if you have time, would you mind to look at the last check of Travis CI build that does not pass anyway. 

Have a nice vacation :)

**Comment by swistakm** [comment]
CI pipeline fixed.

Your change is released on PyPI as 0.6.0 version. Thanks again for your contribution!

**Comment by anlcnydn** [comment]
Hey,

You are welcome. It was a pleasure to me.

I thank you too for quick review, merge, release and fix of CI. 

We all are strong together, thanks to open source. Hurray! May the force be with all of us!

Happy coding.

**Pull request merged**
